using Notifications;
using System.Windows;

namespace WinRTComponent.WPF
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void OnShowNotification(object sender, RoutedEventArgs e)
        {
            NotificationHelper helper = new NotificationHelper();
            helper.ShowNotification("This is a notification", "This is a notification generated by a Win32 app");
        }
    }
}
